### ISSUE TITLE
Unknown packages

### ISSUE THREAD

**Issue by tobybatch** [devgateway/geocoder-ie#18]
Anaconda can't find the following packages:

- pycorenlp
- lxlm
- flask_cors
- sner

Which channels should I add to find them?

I am running this:

```
conda config --add channels conda-forge
conda config --add channels pypi
conda config --add channels brittainhard
conda config --add channels contango
conda install --yes --file requirements.txt
```

**Comment by sdimunzio** [comment]
You can install them using pip, under the conda environment

**Comment by tobybatch** [comment]
@sdimunzio, will you update the readme to cover that please?
