### ISSUE TITLE
pdfminer incompatibility

### ISSUE THREAD

**Issue by tobybatch** [devgateway/geocoder-ie#19]
Running ```conda install --yes --file requirements.txt``` results in:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pdfminer -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

I have removed these packages from requirements.txt (see #18):
- sed -i '/pycorenlp/d' requirements.txt
- sed -i '/lxlm/d' requirements.txt
- sed -i '/flask_cors/d' requirements.txt
- sed -i '/sner/d' requirements.txt

**Comment by sdimunzio** [comment]
You have to install pdfminder.six, I will update the requirements file.
