### ISSUE TITLE
Errors to the standard Err

### ISSUE THREAD

**Issue by tobybatch** [devgateway/geocoder-ie#20]
I'm getting an error "Unexpected error" trying to geocode an XML file.  Can you fix it so errors are out put to the std err please?

I attache to the std out for the json and std err for process output and this error was appearing to me to be un-parsable json.

**Comment by sdimunzio** [comment]
Can you attach the xml file?

**Comment by tobybatch** [comment]
Sure but it's the error re-direction I'm after. 

https://raw.githubusercontent.com/NeonOpenAG/oagtoolbox/develop/src/OagBundle/Resources/fixtures/after_enrichment_activities.xml
