### ISSUE TITLE
Callbacks going to port 5000 not specified port

### ISSUE THREAD

**Issue by tobybatch** [devgateway/geocoder-ie#31]
Running the geocoder on port 9095 results i this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/docqueue?page=1&state=PROCESSED. (Reason: CORS request did not succeed).[Learn More]
Error: "Network Error"

It seems the service is calling back to itself on the default port.

**Comment by sdimunzio** [comment]
To solve that problem, you will need to update  the API_ROOT variable and recompile the UI.
Please look at the file ui/src/main.js , in line  #8 is where window.API_ROOT is set to http://localhost:5000.
After updating the variable you have  to run the following commands in /geocoder-ie/ui folder
 `npm install`
`npm run build`
